# Site settings
# Theme/Hydejack settings: https://hydejack.com/docs/config/

title: Kraus Dev House
email: jason@krausdevhouse.com
description: >-
   I am a developer for hire and am shovel ready. Beyond delivering code, I can help with technology roadmap development, architecture design, code review, visual strategic analysis and hiring. 
   My approach is holistic and considerate of the long-term goals and strategic positioning of your organization. 
   I pride myself on being able to provide tailored solutions for my clients, and I am dedicated to participating in the innovation of my field.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://krausdevhouse.com"
author:
  social:
    github: zbyte64
    mastodon: zbyte64
favicon: /favicon.ico
accent_image: /sidebar_accent.png
logo: /Kraus_Dev_House_Logo_Color.png

menu:
  - title: Resume
    url: /resume/
  - title: About
    url: /

# Build settings
theme: jekyll-theme-hydejack
# remote_theme: hydecorp/hydejack@v9.1.6
plugins:
  - jekyll-feed
  - jekyll-include-cache

google_analytics: G-5BMWY55XVN

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
