# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Kraus Dev House
email: jason@krausdevhouse.com
description: >- # this means to ignore newlines until "baseurl:"
   Kraus Dev House offers strategic technical consulting to software companies. As an independent consultant, I provide a range of services, including technology roadmap development, architecture design, code review, project management, visual strategic analysis. 
   My approach is holistic and considerate of the long-term goals and strategic positioning of your organization. 
   I pride myself on being able to provide tailored solutions for my clients, and I am dedicated to participating in the innovation of my field.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://krausdevhouse.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: zbyte64
github_username: zbyte64
favicon: /favicon.ico
accent_image: /sidebar_accent.png
logo: /Kraus_Dev_House_Logo_Color.png

# Build settings
# theme: jekyll-theme-hydejack
remote_theme: hydecorp/hydejack@v9.1.6
plugins:
  - jekyll-feed
  - jekyll-include-cache

google_analytics: G-5BMWY55XVN

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
